# vim: set filetype=ampl : #

#################################################
### Heuristic to make the variables integer   ###
### Eugenio Gianniti 24/12/2014               ###
#################################################

printf "Heuristic to make the variables integer\n\n";

include ../utils/order_AMs.run;
let {i in AM} r[i] := ceil (r[i]);
let {i in AM} gamma[i] := ceil (gamma[i]);

let {i in AM} sM[i] := ceil (sM[i]);
let {i in AM} sR[i] := ceil (sR[i]);
