# vim: set filetype=ampl : #

################################################################
### Params for the heuristic to make the variables integer   ###
### Eugenio Gianniti 22/02/2015                              ###
################################################################

param idx {i in AM} integer >=0;
param i_aux integer >=0;
param swap_aux integer >=0;
param t {i in AM} >=0 default 0;
