package it.polimi.diceH2020.SPACE4CloudWS.stateMachine;

public enum Events {
	MIGRATE, 
	TO_CHARGED_INPUTDATA, 
	TO_CHARGED_INITSOLUTION, 
	TO_EVALUATED_INITSOLUTION,
	STOP, 
	RESET, 
	FINISH, 
	TO_RUNNING_INIT, 
	TO_EVALUATING_INIT,
	TO_RUNNING_LS
}
