package it.polimi.diceH2020.SPACE4CloudWS.stateMachine;

public enum States {
	STARTING,
	IDLE,
	CHARGED_INPUTDATA,
	CHARGED_INITSOLUTION,
	EVALUATED_INITSOLUTION,
	FINISH,
	ERROR, 
	RUNNING_INIT, 
	EVALUATING_INIT,
	RUNNING_LS
}
